apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hellojava
    version: v1
  name: hellojava
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: hellojava
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hellojava
        version: v1
    spec:
      containers:
      - image: 
        imagePullPolicy: IfNotPresent
        name: hellojava
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hellojava
  name: hellojava
  namespace: default
spec:
  ports:
  - nodePort: 32207
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hellojava 
  sessionAffinity: None
  type: LoadBalancer